# Generated by Django 2.0.3 on 2018-03-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_auto_20180330_0042'),
        ('accounts', '0005_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
