# Generated by Django 2.0.3 on 2018-03-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_auto_20180330_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name_plural': 'BlogPost'},
        ),
    ]
