# Generated by Django 2.0.3 on 2018-03-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_auto_20180330_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
