# Generated by Django 2.0.3 on 2018-04-01 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_auto_20180330_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_creator',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
