# Generated by Django 2.0.3 on 2018-04-01 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0005_auto_20180401_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_creator',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
